-- Starter seed — small sample set per company/branch so the practice feature has real
-- data to show. Expand via later Vn__ migrations as more questions are curated;
-- do not edit this file once it has run in any environment.

INSERT INTO company_questions (company_name, role, category, difficulty, question, ideal_answer, tags) VALUES
('Google', 'Software Engineer', 'DSA', 'MEDIUM', 'Given an array of integers, find two numbers that add up to a target sum.', 'Use a hash map to store seen values and their indices; check complement in O(n) time, O(n) space.', ARRAY['arrays','hashmap','two-pointer']),
('Google', 'Software Engineer', 'System Design', 'HARD', 'Design a URL shortening service like TinyURL.', 'Cover: base62 encoding vs hashing, DB schema, read-heavy caching, collision handling, custom aliases.', ARRAY['system-design','scalability']),
('Microsoft', 'Software Engineer', 'DSA', 'MEDIUM', 'Reverse a linked list iteratively and recursively.', 'Iteratively track prev/curr/next pointers; recursively reverse the rest then fix current node''s next pointer.', ARRAY['linked-list','recursion']),
('Microsoft', 'Software Engineer', 'Behavioral', 'EASY', 'Tell me about a time you disagreed with a teammate on a technical decision.', 'STAR format: situation, the technical disagreement, how you resolved it collaboratively, outcome.', ARRAY['behavioral','communication']),
('Amazon', 'SDE-1', 'Behavioral', 'MEDIUM', 'Describe a time you had to deliver a project under a tight deadline.', 'Map to Amazon Leadership Principles: Deliver Results / Ownership. Use STAR, quantify the outcome.', ARRAY['behavioral','leadership-principles']),
('Amazon', 'SDE-1', 'DSA', 'HARD', 'Find the shortest path in a weighted graph with non-negative edges.', 'Dijkstra''s algorithm with a min-heap; explain time complexity O((V+E) log V).', ARRAY['graphs','dijkstra']),
('TCS', 'System Engineer', 'Aptitude', 'EASY', 'A train 100m long crosses a platform of 200m in 20 seconds. Find its speed.', 'Total distance = 300m in 20s => speed = 15 m/s = 54 km/h.', ARRAY['aptitude','speed-distance']),
('TCS', 'System Engineer', 'Technical', 'EASY', 'What is the difference between a process and a thread?', 'Process: independent memory space, heavyweight. Thread: shares memory within a process, lightweight, faster context switch.', ARRAY['os','fundamentals']),
('Infosys', 'System Engineer', 'Technical', 'EASY', 'Explain normalization in databases and its normal forms.', '1NF: atomic columns. 2NF: no partial dependency on composite key. 3NF: no transitive dependency. Reduces redundancy.', ARRAY['dbms','normalization']);

INSERT INTO branch_questions (branch, subject, difficulty, question, ideal_answer, tags) VALUES
('CSE', 'Operating Systems', 'MEDIUM', 'Explain deadlock and the four necessary conditions for it to occur.', 'Mutual exclusion, hold and wait, no preemption, circular wait — all four must hold simultaneously.', ARRAY['os','deadlock']),
('CSE', 'DBMS', 'MEDIUM', 'What is the difference between a clustered and non-clustered index?', 'Clustered index physically orders table rows by key (one per table); non-clustered is a separate structure pointing to rows (many per table).', ARRAY['dbms','indexing']),
('ECE', 'Digital Electronics', 'EASY', 'Convert the decimal number 45 to binary.', '45 = 101101 in binary (32+8+4+1).', ARRAY['digital-electronics','number-systems']),
('ECE', 'Communication Systems', 'MEDIUM', 'What is the difference between AM and FM modulation?', 'AM varies amplitude of carrier with message signal (simple, noise-prone); FM varies frequency (more bandwidth, better noise immunity).', ARRAY['communication','modulation']),
('Mechanical', 'Thermodynamics', 'MEDIUM', 'State the second law of thermodynamics and give a real-world implication.', 'Entropy of an isolated system never decreases; implies no heat engine can be 100% efficient (Carnot limit).', ARRAY['thermodynamics','entropy']),
('Mechanical', 'Strength of Materials', 'EASY', 'Define stress and strain and state Hooke''s Law.', 'Stress = force/area, strain = deformation/original length. Hooke''s Law: stress is proportional to strain within elastic limit (σ = Eε).', ARRAY['som','elasticity']),
('Electrical', 'Circuit Theory', 'EASY', 'State Kirchhoff''s Current Law and Voltage Law.', 'KCL: sum of currents entering a node equals sum leaving. KVL: sum of voltages around any closed loop is zero.', ARRAY['circuits','kirchhoff']);
