-- MP localization: add regional recruiters students in Madhya Pradesh commonly interview with.

INSERT INTO company_questions (company_name, role, category, difficulty, question, ideal_answer, tags) VALUES
('TCS Bhopal', 'Assistant System Engineer', 'Technical', 'EASY', 'What is the difference between DDL, DML, and DCL commands in SQL?', 'DDL (CREATE, ALTER, DROP) defines schema structure; DML (SELECT, INSERT, UPDATE, DELETE) manipulates data; DCL (GRANT, REVOKE) manages access permissions.', ARRAY['sql','fundamentals']),
('TCS Bhopal', 'Assistant System Engineer', 'Aptitude', 'EASY', 'If a shopkeeper marks up a product by 25% and then gives a 10% discount, what is the net profit percentage?', 'Let CP = 100. Marked price = 125. After 10% discount = 112.5. Net profit = 12.5%.', ARRAY['aptitude','profit-loss']),
('TCS Bhopal', 'Assistant System Engineer', 'Behavioral', 'EASY', 'Why do you want to join TCS?', 'Focus on TCS''s scale, learning culture (TCS iON, Ninja/Digital programs), and alignment with long-term stability and growth goals.', ARRAY['behavioral','company-fit']),
('Infosys Indore', 'Systems Engineer', 'Technical', 'EASY', 'Explain the difference between compile-time and run-time polymorphism with examples.', 'Compile-time: method overloading, resolved by compiler. Run-time: method overriding, resolved via dynamic dispatch using virtual/overridden methods.', ARRAY['oops','polymorphism']),
('Infosys Indore', 'Systems Engineer', 'Aptitude', 'MEDIUM', 'A and B can complete a work in 12 and 18 days respectively. How long will they take working together?', 'Combined rate = 1/12 + 1/18 = 5/36 per day. Time = 36/5 = 7.2 days.', ARRAY['aptitude','time-work']),
('Infosys Indore', 'Systems Engineer', 'Behavioral', 'EASY', 'Tell us about a project where you had to learn a new technology quickly.', 'STAR format: context requiring the new skill, how you ramped up (docs/courses/practice), the outcome delivered.', ARRAY['behavioral','learning-agility']),
('CDAC Pune', 'Project Engineer', 'Technical', 'MEDIUM', 'What is the difference between multithreading and multiprocessing in operating systems?', 'Multithreading: multiple threads share the same process memory, lightweight context switch. Multiprocessing: separate processes with independent memory, higher isolation, more overhead.', ARRAY['os','concurrency']),
('CDAC Pune', 'Project Engineer', 'Technical', 'MEDIUM', 'Explain the CDAC PG-DAC curriculum relevance to a Java/embedded systems role.', 'Connect coursework (Java, embedded C, networking) to the specific role''s requirements; highlight any certification project.', ARRAY['cdac','career-context']),
('CDAC Pune', 'Project Engineer', 'Behavioral', 'EASY', 'Why do you want to work on government-funded R&D projects rather than a private product company?', 'Discuss interest in mission-driven work, long-term research depth, and contributing to national technology self-reliance (Atmanirbhar Bharat).', ARRAY['behavioral','motivation']),
('DRDO', 'Scientist/Engineer', 'Technical', 'HARD', 'Explain the working principle of radar and its key components.', 'Radar emits EM pulses, measures reflected signal time-of-flight to compute range; components include transmitter, antenna, receiver, signal processor.', ARRAY['drdo','electronics','radar']),
('DRDO', 'Scientist/Engineer', 'Technical', 'MEDIUM', 'What is the difference between open-loop and closed-loop control systems?', 'Open-loop: output does not affect input (no feedback), simple but inaccurate. Closed-loop: output is fed back to adjust input, more accurate and self-correcting.', ARRAY['control-systems','engineering']),
('DRDO', 'Scientist/Engineer', 'Behavioral', 'MEDIUM', 'Why is a career in defence research meaningful to you?', 'Discuss national security contribution, interest in applied research over pure commercial product work, and long-term technical depth in a niche domain.', ARRAY['behavioral','motivation']);
