-- Expanded government exam interview question bank (SSB/UPSC/BANK_PO/SSC_RAILWAY/RESEARCH_ORG).

-- Government interview question bank (75 rows: 15 per exam_type)

INSERT INTO government_interview_questions (exam_type, category, difficulty, question, ideal_answer, tags) VALUES
('SSB', 'Personal Background', 'EASY', 'Tell us about yourself, your family and your educational background.', 'A strong answer is concise, truthful and well structured, covering family, schooling, hobbies and achievements without exaggeration or rehearsed-sounding claims.', ARRAY['self-introduction','family','background']),
('SSB', 'Personal Background', 'EASY', 'Why do you want to join the armed forces?', 'Should show genuine motivation such as service, discipline and challenge rather than only job security, supported by a real incident or influence that shaped the choice.', ARRAY['motivation','defence','career']),
('SSB', 'Personal Background', 'EASY', 'What are your hobbies, and how much time do you give to them?', 'Mention real hobbies you can discuss in depth, with regularity, skills gained and a recent example, since follow-up questions will test authenticity.', ARRAY['hobbies','personality','self-awareness']),
('SSB', 'Personal Background', 'MEDIUM', 'What are your strengths and weaknesses? What are you doing to improve the weaknesses?', 'Give honest, specific traits backed by examples, and show concrete steps taken to work on weaknesses rather than disguised strengths.', ARRAY['self-assessment','strengths','weaknesses']),
('SSB', 'Personal Background', 'MEDIUM', 'What will you do if you are not selected in the SSB?', 'Show resilience and a realistic Plan B, such as reattempting after feedback while pursuing another worthwhile path, without sounding desperate or indifferent.', ARRAY['resilience','planning','career']),
('SSB', 'Leadership', 'MEDIUM', 'Describe a situation where you had to lead a team under pressure with limited resources.', 'Look for ownership, calm decision-making under pressure, delegation, and a concrete outcome.', ARRAY['leadership','pressure','teamwork']),
('SSB', 'Leadership', 'MEDIUM', 'Have you ever held a position of responsibility, such as captain or class representative? What did you learn?', 'Describe the role honestly, specific responsibilities, a challenge faced and what it taught about motivating and managing people.', ARRAY['leadership','responsibility','experience']),
('SSB', 'Leadership', 'HARD', 'You are leading a group and a team member openly refuses to follow your decision. How would you handle it?', 'Show listening to the concern first, maintaining authority without ego, protecting group cohesion, and a private follow-up discussion after the task.', ARRAY['leadership','conflict','discipline']),
('SSB', 'Leadership', 'EASY', 'Do you think a leader is born or made?', 'Take a clear position, usually that leadership is largely developed through experience and training, and support it with a short personal example.', ARRAY['leadership','opinion','qualities']),
('SSB', 'Situation Reaction', 'EASY', 'You are travelling by train and see a fellow passenger being harassed by a group of youths. What will you do?', 'Prioritise safety, alert railway staff or police, mobilise other passengers and help the victim, showing courage balanced with good judgement.', ARRAY['situation-reaction','courage','civic-sense']),
('SSB', 'Situation Reaction', 'MEDIUM', 'You are at a picnic and one of your friends starts drowning in a river. What is your immediate reaction?', 'Act quickly and sensibly: call for help, throw a rope or floating object, and enter the water only if trained, while keeping yourself safe.', ARRAY['situation-reaction','presence-of-mind','safety']),
('SSB', 'Situation Reaction', 'MEDIUM', 'During a group trek you realise two members are missing and darkness is approaching. What do you do?', 'Stay calm, account for the rest of the group, set up a search plan, inform authorities if needed and avoid splitting into unsafe small parties.', ARRAY['situation-reaction','planning','responsibility']),
('SSB', 'Situation Reaction', 'HARD', 'You discover that a close friend at your workplace is involved in serious wrongdoing. What is your reaction?', 'Show integrity over friendship: counsel him first, then report through the proper channel if he does not correct course, in a fair and non-hasty manner.', ARRAY['situation-reaction','integrity','dilemma']),
('SSB', 'Current Affairs', 'MEDIUM', 'What are the major security challenges currently facing India along its borders?', 'Mention specific, recent and balanced points about border situations, infiltration and cross-border threats, along with the role of the armed forces and diplomacy.', ARRAY['security','borders','current-affairs']),
('SSB', 'General Knowledge', 'EASY', 'Name the three services of the Indian armed forces and explain the role of each.', 'Correctly name the Army, Navy and Air Force and describe their primary roles on land, sea and air, showing basic awareness expected of a defence aspirant.', ARRAY['armed-forces','general-knowledge','basics']);

INSERT INTO government_interview_questions (exam_type, category, difficulty, question, ideal_answer, tags) VALUES
('UPSC', 'Personal Background', 'EASY', 'Tell us about your home district and what it is known for.', 'Cover geography, economy, culture and one or two real developmental issues of the district, showing awareness of your own background beyond Wikipedia facts.', ARRAY['home-district','background','awareness']),
('UPSC', 'Personal Background', 'EASY', 'Why do you want to join the civil services?', 'Give a genuine, specific motivation tied to public service and impact, avoiding cliches like power or status, and link it to your own experiences.', ARRAY['motivation','civil-services','career']),
('UPSC', 'Personal Background', 'EASY', 'You have an engineering or professional degree. Why are you leaving that field for the civil services?', 'Explain the shift honestly, showing how your skills will help in administration and why you see greater scope for public impact in this role.', ARRAY['career-switch','motivation','education']),
('UPSC', 'Personal Background', 'MEDIUM', 'What is your plan B if you do not make it this time?', 'Show a realistic, well-thought alternative and a mature attitude toward failure, while remaining committed and not appearing half-hearted.', ARRAY['resilience','planning','career']),
('UPSC', 'Personal Background', 'MEDIUM', 'How do you handle stress, and what do you do when you are criticised?', 'Describe practical coping habits and an example of accepting criticism constructively, showing emotional stability and openness to feedback.', ARRAY['stress','emotional-intelligence','self-awareness']),
('UPSC', 'Optional Subject', 'MEDIUM', 'Why did you choose your optional subject, and how is it relevant to administration?', 'Link the choice to genuine interest and background, and give concrete examples of how its concepts help in policy and governance.', ARRAY['optional-subject','relevance','administration']),
('UPSC', 'Optional Subject', 'HARD', 'Pick a recent debate or theory in your optional subject and explain how it applies to a current policy problem.', 'Show conceptual clarity, a balanced presentation of competing viewpoints and a practical application to a real policy example.', ARRAY['optional-subject','analysis','policy']),
('UPSC', 'Current Affairs', 'MEDIUM', 'What are the key challenges and opportunities in India''s energy transition?', 'Cover renewable targets, grid and storage challenges, coal dependence, cost and just-transition concerns, ending with a balanced way forward.', ARRAY['energy','climate','current-affairs']),
('UPSC', 'Current Affairs', 'MEDIUM', 'How should India balance its relationships with major powers in the present global order?', 'Discuss strategic autonomy, multi-alignment, economic interests and regional neighbourhood, with a nuanced and non-partisan stance.', ARRAY['foreign-policy','geopolitics','current-affairs']),
('UPSC', 'Ethics', 'EASY', 'What does integrity mean to you in a public servant?', 'Define integrity as consistency between values and action, supported by a short example and its importance in preventing corruption.', ARRAY['ethics','integrity','values']),
('UPSC', 'Ethics', 'MEDIUM', 'You are a district officer and a powerful local leader asks you to bend rules for a project. What will you do?', 'Uphold the rule of law politely but firmly, explore legitimate alternatives, document the interaction and escalate if pressure continues.', ARRAY['ethics','pressure','rule-of-law']),
('UPSC', 'Ethics', 'HARD', 'A rule you are bound to follow will cause serious hardship to a vulnerable group. How do you resolve the conflict?', 'Show the balance between legality and compassion, exploring discretion, representation to higher authorities and policy feedback without breaking the law.', ARRAY['ethics','dilemma','compassion']),
('UPSC', 'Opinion/Policy', 'MEDIUM', 'Do you think reservation should continue based on caste, or should economic criteria be used?', 'Present a balanced view covering social justice, evidence on outcomes and the role of economic factors, avoiding extreme positions.', ARRAY['reservation','social-justice','policy']),
('UPSC', 'Opinion/Policy', 'EASY', 'What is your opinion on using technology and e-governance to reduce corruption?', 'Give examples such as direct benefit transfer and online services, and acknowledge limits like the digital divide and data privacy.', ARRAY['e-governance','technology','corruption']),
('UPSC', 'Opinion/Policy', 'HARD', 'Should India have a Uniform Civil Code? Defend your view with arguments for and against.', 'Show structured reasoning, constitutional awareness, sensitivity to diversity and gender justice, and a considered conclusion rather than a slogan.', ARRAY['ucc','constitution','policy-debate']);

INSERT INTO government_interview_questions (exam_type, category, difficulty, question, ideal_answer, tags) VALUES
('BANK_PO', 'Personal Background', 'EASY', 'Tell us about yourself and your educational background.', 'Be brief and organised, covering education, key achievements and interests, and connect them to the banking role.', ARRAY['self-introduction','education','background']),
('BANK_PO', 'Personal Background', 'EASY', 'Why do you want to become a Bank PO?', 'Link genuine interest in finance, customer interaction and career growth to the role, avoiding an answer that is only about job security.', ARRAY['motivation','career','banking']),
('BANK_PO', 'Personal Background', 'EASY', 'Are you willing to work in any part of India, including rural branches?', 'Express willingness with a positive attitude, and show understanding that rural postings are central to financial inclusion.', ARRAY['transfer','rural-banking','flexibility']),
('BANK_PO', 'Personal Background', 'MEDIUM', 'You have a gap in your studies or work history. Can you explain it?', 'Give an honest, brief explanation focusing on what you learned or did during that time and why you are ready now.', ARRAY['career-gap','honesty','self-awareness']),
('BANK_PO', 'Banking Awareness', 'EASY', 'What is the difference between the repo rate and the reverse repo rate?', 'Repo is the rate at which RBI lends short-term funds to banks, while reverse repo is the rate at which it borrows from banks; note their use in controlling liquidity.', ARRAY['monetary-policy','repo-rate','rbi']),
('BANK_PO', 'Banking Awareness', 'MEDIUM', 'What is a Non-Performing Asset, and how does it affect a bank?', 'Define an NPA as a loan with unpaid interest or principal beyond 90 days, and explain impact on profitability, provisioning and lending capacity.', ARRAY['npa','asset-quality','banking']),
('BANK_PO', 'Banking Awareness', 'MEDIUM', 'Explain CRR and SLR and why the RBI uses them.', 'CRR is the share of deposits kept with RBI in cash and SLR the share kept in liquid assets; both manage liquidity and credit expansion.', ARRAY['crr','slr','monetary-policy']),
('BANK_PO', 'Banking Awareness', 'MEDIUM', 'What is KYC, and why is it important for banks?', 'Explain identity verification for customers and how it prevents fraud, money laundering and terror financing while supporting regulatory compliance.', ARRAY['kyc','compliance','aml']),
('BANK_PO', 'Banking Awareness', 'HARD', 'How do the Basel III norms affect banks, and why were they introduced?', 'Discuss higher capital quality, leverage and liquidity requirements introduced after the 2008 crisis to strengthen bank resilience.', ARRAY['basel-iii','capital-adequacy','regulation']),
('BANK_PO', 'Current Affairs', 'MEDIUM', 'What do you know about the Unified Payments Interface and its impact on banking?', 'Describe real-time interoperable payments, its growth in digital transactions, benefits for inclusion and challenges like fraud and outages.', ARRAY['upi','digital-payments','fintech']),
('BANK_PO', 'Current Affairs', 'MEDIUM', 'What is the latest development in the RBI monetary policy, and what does it mean for borrowers?', 'State the recent policy stance accurately and explain the effect on loan rates, EMIs, inflation and growth in simple terms.', ARRAY['rbi','monetary-policy','current-affairs']),
('BANK_PO', 'Current Affairs', 'HARD', 'What are the pros and cons of the merger of public sector banks in recent years?', 'Cover scale, efficiency and capital benefits against integration challenges, job and culture issues and reduced competition.', ARRAY['bank-merger','psu-banks','policy']),
('BANK_PO', 'Situational', 'EASY', 'A customer is angry because his transaction failed. How will you handle him?', 'Listen calmly, empathise, check the issue, explain the resolution timeline and follow up, showing patience and customer focus.', ARRAY['customer-service','communication','situational']),
('BANK_PO', 'Situational', 'MEDIUM', 'Your branch has a high sales target and a customer needs a product that is not suitable for him. What do you do?', 'Put ethical selling and customer interest first, offer a suitable product and explain the target pressure honestly to your manager.', ARRAY['ethics','sales','customer-trust']),
('BANK_PO', 'Situational', 'HARD', 'You notice a senior colleague bypassing a compliance procedure to close a loan faster. How will you react?', 'Raise it first with the colleague, and escalate through the proper channel if ignored, emphasising compliance and risk to the bank.', ARRAY['compliance','integrity','escalation']);

INSERT INTO government_interview_questions (exam_type, category, difficulty, question, ideal_answer, tags) VALUES
('SSC_RAILWAY', 'Personal Background', 'EASY', 'Tell us about yourself and your family.', 'Give a short, truthful introduction covering education, family and interests, delivered confidently and without unnecessary detail.', ARRAY['self-introduction','family','background']),
('SSC_RAILWAY', 'Personal Background', 'EASY', 'Why do you want a government job, and why this department?', 'Show interest in public service, stability and growth, plus some knowledge of the department and its work.', ARRAY['motivation','government-job','career']),
('SSC_RAILWAY', 'Personal Background', 'EASY', 'Are you ready to accept a posting away from your home town?', 'Express willingness with a positive attitude and show an understanding that transferable postings are part of the job.', ARRAY['transfer','flexibility','attitude']),
('SSC_RAILWAY', 'Personal Background', 'MEDIUM', 'What will you do if you are posted in a role that is not your first preference?', 'Show adaptability and a commitment to perform well in any role, using it as a learning opportunity.', ARRAY['adaptability','attitude','career']),
('SSC_RAILWAY', 'Personal Background', 'MEDIUM', 'Describe a time you worked under pressure or a tight deadline.', 'Give a real example, covering how you prioritised, stayed calm and the outcome, showing reliability.', ARRAY['pressure','deadlines','work-ethic']),
('SSC_RAILWAY', 'General Knowledge', 'EASY', 'When was the first passenger train run in India, and between which stations?', 'It ran in 1853 between Bombay and Thane, a basic fact showing awareness of Indian Railways heritage.', ARRAY['railways','history','general-knowledge']),
('SSC_RAILWAY', 'General Knowledge', 'EASY', 'How many zones does Indian Railways have, and what are some of them?', 'State the count correctly (commonly 17 zones) and name a few such as Northern, Central and Western, showing familiarity with the system.', ARRAY['railways','zones','general-knowledge']),
('SSC_RAILWAY', 'General Knowledge', 'MEDIUM', 'What is the role of the Railway Board and who heads it?', 'Explain that it is the apex body managing policy and administration of Indian Railways, and name the current chairperson accurately.', ARRAY['railway-board','administration','general-knowledge']),
('SSC_RAILWAY', 'General Knowledge', 'MEDIUM', 'What is the Kavach system, and why is it important?', 'Describe it as an indigenous automatic train protection system designed to prevent collisions and improve safety.', ARRAY['kavach','railway-safety','technology']),
('SSC_RAILWAY', 'General Knowledge', 'HARD', 'What are the major initiatives for modernising Indian Railways, such as dedicated freight corridors and electrification?', 'Mention freight corridors, electrification progress, modern trains and station redevelopment, with an awareness of their purpose.', ARRAY['railway-modernisation','infrastructure','current-affairs']),
('SSC_RAILWAY', 'Technical', 'EASY', 'What is the difference between AC and DC current?', 'AC changes direction periodically while DC flows in one direction; mention that railways use both in traction systems.', ARRAY['electrical','basics','traction']),
('SSC_RAILWAY', 'Technical', 'MEDIUM', 'Why are signals and interlocking important for railway safety?', 'Explain that interlocking prevents conflicting train movements by controlling signals and points, reducing the risk of accidents.', ARRAY['signalling','interlocking','safety']),
('SSC_RAILWAY', 'Technical', 'MEDIUM', 'What is the function of a pantograph in an electric locomotive?', 'It collects current from overhead lines and supplies it to the locomotive, requiring proper contact and maintenance.', ARRAY['electric-traction','pantograph','technical']),
('SSC_RAILWAY', 'Technical', 'MEDIUM', 'How do you ensure accuracy and safety when working with records or data in an office role?', 'Describe double-checking, following SOPs, maintaining proper documentation and escalating discrepancies promptly.', ARRAY['accuracy','records','office-work']),
('SSC_RAILWAY', 'Technical', 'HARD', 'What are the basic causes of a derailment, and how can they be minimised?', 'Mention track defects, rolling stock faults, human error and speed, and explain preventive measures like inspections, maintenance and technology.', ARRAY['derailment','safety','maintenance']);

INSERT INTO government_interview_questions (exam_type, category, difficulty, question, ideal_answer, tags) VALUES
('RESEARCH_ORG', 'Personal Background', 'EASY', 'Tell us about your academic background and your final-year project.', 'Summarise your education and explain the project clearly, covering the objective, your own contribution, method and result.', ARRAY['self-introduction','project','education']),
('RESEARCH_ORG', 'Personal Background', 'EASY', 'What are your strengths and weaknesses as a researcher or engineer?', 'Be honest and specific with examples, and show steps taken to improve your weaknesses.', ARRAY['self-assessment','strengths','weaknesses']),
('RESEARCH_ORG', 'Personal Background', 'MEDIUM', 'Describe a time you faced failure in an experiment or project and what you did next.', 'Show analysis of what went wrong, persistence, learning and a concrete corrective outcome.', ARRAY['failure','resilience','learning']),
('RESEARCH_ORG', 'Motivation', 'EASY', 'Why do you want to join this organisation instead of the private sector?', 'Show interest in national-importance projects, long-term research and mission-driven work, with real knowledge of the organisation.', ARRAY['motivation','public-sector','mission']),
('RESEARCH_ORG', 'Motivation', 'EASY', 'What do you know about the recent missions or projects of this organisation?', 'Mention recent, accurate projects and explain why they interest you, showing preparation and curiosity.', ARRAY['organisation-knowledge','missions','preparation']),
('RESEARCH_ORG', 'Motivation', 'MEDIUM', 'Where do you see yourself in the next five to ten years in research?', 'Show a realistic plan for skill building, contribution to projects and growth aligned to the organisation, without being vague.', ARRAY['career-goals','growth','vision']),
('RESEARCH_ORG', 'Motivation', 'MEDIUM', 'Are you comfortable with long hours and work in remote or secure locations?', 'Show commitment and flexibility while demonstrating an understanding that mission-critical projects need dedication.', ARRAY['commitment','flexibility','work-environment']),
('RESEARCH_ORG', 'Technical', 'MEDIUM', 'Explain the working principle of a core concept from your engineering or science discipline in simple terms.', 'Explain accurately with a clear structure and a practical example, showing depth beyond textbook definitions.', ARRAY['fundamentals','core-subject','communication']),
('RESEARCH_ORG', 'Technical', 'MEDIUM', 'How would you approach designing a system when requirements are incomplete or changing?', 'Describe clarifying requirements, building modular designs, iterating with feedback and documenting assumptions.', ARRAY['system-design','requirements','problem-solving']),
('RESEARCH_ORG', 'Technical', 'HARD', 'Discuss the key challenges in developing indigenous defence or space technologies.', 'Cover technology gaps, testing and reliability, supply chain, funding and skill requirements, and suggest ways forward.', ARRAY['indigenisation','defence-tech','space']),
('RESEARCH_ORG', 'Technical', 'EASY', 'What is the difference between a theoretical model and an experimental result, and why do both matter?', 'Explain that models predict and explain, while experiments validate, and that agreement or mismatch drives scientific progress.', ARRAY['methodology','science-basics','validation']),
('RESEARCH_ORG', 'Research Aptitude', 'MEDIUM', 'How do you choose a research problem, and how do you know it is worth pursuing?', 'Discuss literature review, identifying gaps, feasibility, relevance and potential impact.', ARRAY['research-problem','literature-review','planning']),
('RESEARCH_ORG', 'Research Aptitude', 'MEDIUM', 'How would you handle results that contradict your hypothesis?', 'Check for errors first, then accept the data honestly, revise the hypothesis and report findings transparently.', ARRAY['hypothesis','integrity','data-analysis']),
('RESEARCH_ORG', 'Research Aptitude', 'HARD', 'How would you plan and manage a research project with limited budget and a strict deadline?', 'Show prioritisation, milestone planning, risk management, resource sharing and stakeholder communication.', ARRAY['project-management','risk','planning']),
('RESEARCH_ORG', 'Research Aptitude', 'EASY', 'Why is reproducibility important in research?', 'Explain that reproducible results build trust, enable verification by others and form the foundation for further work.', ARRAY['reproducibility','research-ethics','methodology']);
