-- Curated starter set of real government recruitment schemes/exams. Salary bands use public
-- 7th CPC pay levels where known. exam_cycle is descriptive (real dates vary yearly and are
-- not asserted as exact) — always points to the official application_link for current dates.
INSERT INTO government_jobs (code, title, organization, category, eligible_branches, min_cgpa, exam_name, application_link, exam_cycle, salary, eligibility, tags) VALUES

-- Central Government Tech
('GOV001', 'Scientist B', 'National Informatics Centre (NIC)', 'CENTRAL_GOVT', ARRAY['CSE','IT','ECE'], 6.0, 'NIC Scientist B', 'https://www.nic.in/careers/', 'Notification: varies, released on nic.in careers page', '₹56,100 - ₹1,77,500 (Level 10)', 'B.E/B.Tech in CSE/IT/ECE with 60% marks', ARRAY['tech','central','permanent']),
('GOV002', 'Project Engineer', 'Centre for Development of Advanced Computing (CDAC)', 'CENTRAL_GOVT', ARRAY['CSE','IT'], 6.5, 'CDAC Recruitment', 'https://www.cdac.in/index.aspx?id=careers', 'Rolling recruitment drives, check careers page', '₹40,000 - ₹60,000/month (contractual)', 'B.E/B.Tech CSE/IT, fresher or experienced', ARRAY['tech','central','contractual']),
('GOV003', 'Scientist / Engineer', 'Defence Research and Development Organisation (DRDO)', 'CENTRAL_GOVT', ARRAY['ECE','CSE','MECH','EEE'], 6.5, 'DRDO CEPTAM / SET Exam', 'https://drdo.gov.in/drdo/career-opportunities', 'Notification: Jan-Mar, Exam: Apr-Jun (typical)', '₹56,100 - ₹1,77,500 (Level 10)', 'B.E/B.Tech relevant branch, age limit applies', ARRAY['tech','research','central']),
('GOV004', 'Scientist / Engineer', 'Indian Space Research Organisation (ISRO)', 'CENTRAL_GOVT', ARRAY['ALL'], 6.5, 'ISRO Centralised Recruitment Board (ICRB)', 'https://www.isro.gov.in/Careers.html', 'Notification: varies by centre, check ISRO careers', '₹56,100 - ₹1,77,500 (Level 10)', 'B.E/B.Tech with min 65% or CGPA 6.84/10', ARRAY['tech','research','central']),
('GOV005', 'Engineer Trainee', 'Bharat Electronics Limited (BEL)', 'PSU', ARRAY['ECE','EEE'], 6.0, 'BEL Engineer Trainee', 'https://bel-india.in/Career', 'Notification: varies, PSU-driven cycle', '₹40,000 - ₹1,40,000 (E-II grade)', 'B.E/B.Tech ECE/EEE, no active backlogs', ARRAY['psu','tech','permanent']),
('GOV006', 'Engineer Trainee', 'Bharat Heavy Electricals Limited (BHEL)', 'PSU', ARRAY['MECH','EEE'], 6.0, 'BHEL Engineer Trainee', 'https://careers.bhel.in/', 'Notification: varies, PSU-driven cycle', '₹50,000 - ₹1,60,000 (E1 grade)', 'B.E/B.Tech Mech/EEE with min 65%', ARRAY['psu','tech','permanent']),
('GOV007', 'Graduate Trainee', 'Oil and Natural Gas Corporation (ONGC)', 'PSU', ARRAY['ALL'], 6.0, 'ONGC Graduate Trainee', 'https://ongcindia.com/web/eng/careers', 'Notification: varies, PSU-driven cycle', '₹60,000 - ₹1,80,000 (E1 grade)', 'B.E/B.Tech relevant discipline', ARRAY['psu','oil-gas','permanent']),
('GOV008', 'Engineer Trainee', 'NTPC Limited', 'PSU', ARRAY['EEE','MECH','CIVIL'], 6.0, 'NTPC Engineer Trainee', 'https://www.ntpc.co.in/careers', 'Notification: varies, PSU-driven cycle', '₹50,000 - ₹1,60,000 (E1 grade)', 'B.E/B.Tech EEE/Mech/Civil with min 65%', ARRAY['psu','power','permanent']),

-- Banking & Finance
('GOV009', 'Probationary Officer', 'Institute of Banking Personnel Selection (IBPS PO)', 'BANKING', ARRAY['ALL'], NULL, 'IBPS PO', 'https://www.ibps.in/', 'Notification: Aug-Sep, Prelims: Oct, Mains: Nov (typical)', '₹48,480 - ₹85,920 + allowances', 'Any graduate, age 20-30', ARRAY['banking','all-graduates']),
('GOV010', 'Clerk', 'Institute of Banking Personnel Selection (IBPS Clerk)', 'BANKING', ARRAY['ALL'], NULL, 'IBPS Clerk', 'https://www.ibps.in/', 'Notification: Jun-Jul, Prelims: Aug-Sep (typical)', '₹19,900 - ₹47,920 + allowances', 'Any graduate, age 20-28', ARRAY['banking','all-graduates']),
('GOV011', 'Probationary Officer', 'State Bank of India (SBI PO)', 'BANKING', ARRAY['ALL'], NULL, 'SBI PO', 'https://sbi.co.in/web/careers', 'Notification: Apr-May, Prelims: Jun-Jul (typical)', '₹41,960 - ₹80,700 + allowances', 'Any graduate, age 21-30', ARRAY['banking','all-graduates']),
('GOV012', 'Junior Associate (Clerk)', 'State Bank of India (SBI Clerk)', 'BANKING', ARRAY['ALL'], NULL, 'SBI Clerk', 'https://sbi.co.in/web/careers', 'Notification: Dec-Jan, Prelims: Feb-Mar (typical)', '₹19,900 - ₹47,920 + allowances', 'Any graduate, age 20-28', ARRAY['banking','all-graduates']),
('GOV013', 'Grade B Officer', 'Reserve Bank of India (RBI Grade B)', 'BANKING', ARRAY['ALL'], NULL, 'RBI Grade B', 'https://opportunities.rbi.org.in/', 'Notification: Jun-Jul, Phase 1: Aug-Sep (typical)', '₹1,16,900 (basic) + grade pay & allowances', 'Any graduate with min 60%, age 21-30', ARRAY['banking','central-bank','all-graduates']),
('GOV014', 'Grade A Officer', 'National Bank for Agriculture and Rural Development (NABARD)', 'BANKING', ARRAY['ALL'], NULL, 'NABARD Grade A', 'https://www.nabard.org/careers.aspx', 'Notification: Jun-Jul (typical)', '₹1,00,000+ (basic) + allowances', 'Any graduate with min 60%, age 21-30', ARRAY['banking','rural-development']),

-- Railway
('GOV015', 'Junior Engineer', 'Railway Recruitment Board (RRB JE)', 'RAILWAY', ARRAY['CSE','ECE','MECH','CIVIL','EEE'], NULL, 'RRB JE', 'https://www.rrbcdg.gov.in/', 'Notification: varies, check RRB regional site', '₹35,400 (Level 6)', 'Diploma/B.E/B.Tech relevant branch, age 18-33', ARRAY['railway','tech','permanent']),
('GOV016', 'NTPC (Graduate posts)', 'Railway Recruitment Board (RRB NTPC)', 'RAILWAY', ARRAY['ALL'], NULL, 'RRB NTPC', 'https://www.rrbcdg.gov.in/', 'Notification: varies, large-scale recruitment cycle', '₹29,200 - ₹35,400 (Level 5-6)', 'Any graduate, age 18-33', ARRAY['railway','all-graduates']),
('GOV017', 'Group D (Track Maintainer etc.)', 'Railway Recruitment Board (RRB Group D)', 'RAILWAY', ARRAY['ALL'], NULL, 'RRB Group D', 'https://www.rrbcdg.gov.in/', 'Notification: varies, large-scale recruitment cycle', '₹18,000 (Level 1)', '10th pass / ITI, age 18-33', ARRAY['railway','entry-level']),
('GOV018', 'Executive Trainee', 'Dedicated Freight Corridor Corporation (DFCCIL)', 'RAILWAY', ARRAY['CSE','ECE','MECH'], 6.0, 'DFCCIL Executive Trainee', 'https://www.dfccil.com/careers', 'Notification: varies', '₹50,000 - ₹1,60,000 (E1 grade)', 'B.E/B.Tech relevant branch', ARRAY['railway','psu','tech']),

-- State Government (MP-specific)
('GOV019', 'State Service Exam (SAS/DSP/Tehsildar etc.)', 'Madhya Pradesh Public Service Commission (MPPSC)', 'STATE_GOVT', ARRAY['ALL'], NULL, 'MPPSC State Service Exam', 'https://mppsc.mp.gov.in/', 'Notification: varies, annual cycle', 'As per post (Pay Matrix Level 6-11)', 'Any graduate, MP domicile preference for some posts', ARRAY['state','mp','administrative']),
('GOV020', 'Forest Service Officer', 'Madhya Pradesh Public Service Commission (MPPSC Forest)', 'STATE_GOVT', ARRAY['ALL'], NULL, 'MPPSC State Forest Service Exam', 'https://mppsc.mp.gov.in/', 'Notification: varies, annual cycle', 'Pay Matrix Level 10-11', 'Bachelor''s in relevant science/forestry discipline', ARRAY['state','mp','forest']),
('GOV021', 'Sub Inspector', 'Madhya Pradesh Police', 'STATE_GOVT', ARRAY['ALL'], NULL, 'MP Police SI Recruitment', 'https://www.mppolice.gov.in/', 'Notification: varies via mponline.gov.in', 'Pay Matrix Level 7', 'Any graduate, physical eligibility criteria apply', ARRAY['state','mp','police']),
('GOV022', 'Various Posts (Group 2/3/4)', 'MP Employees Selection Board (MP Vyapam / ESB)', 'STATE_GOVT', ARRAY['ALL'], NULL, 'MP Vyapam Various Exams', 'https://esb.mp.gov.in/', 'Notification: rolling throughout the year', 'Varies by post', '10th/12th/Graduate depending on post', ARRAY['state','mp','vyapam']),
('GOV023', 'Junior Engineer', 'MP Paschim Kshetra Vidyut Vitaran Company (MPPKVVCL)', 'STATE_GOVT', ARRAY['EEE'], 6.0, 'MPPKVVCL JE Recruitment', 'https://www.mpwz.co.in/', 'Notification: varies via mponline.gov.in', 'Pay Matrix Level 6-7', 'B.E/B.Tech Electrical/Diploma EEE', ARRAY['state','mp','power']),
('GOV024', 'Junior Engineer (Civil/Mech)', 'MP Public Works Department (PWD)', 'STATE_GOVT', ARRAY['CIVIL','MECH'], 6.0, 'MP PWD JE Recruitment', 'https://mpwd.gov.in/', 'Notification: varies via mponline.gov.in', 'Pay Matrix Level 6-7', 'B.E/B.Tech/Diploma Civil or Mechanical', ARRAY['state','mp','civil']),
('GOV025', 'Probationary Officer', 'MP State Cooperative Bank', 'STATE_GOVT', ARRAY['ALL'], NULL, 'MP Cooperative Bank PO', 'https://apexbank.mp.gov.in/', 'Notification: varies via mponline.gov.in', '₹30,000 - ₹50,000 approx', 'Any graduate, MP domicile required', ARRAY['state','mp','banking']),

-- Defence & Paramilitary
('GOV026', 'Short Service Commission (TES/UES)', 'Indian Army (SSB)', 'DEFENCE', ARRAY['ALL'], NULL, 'SSB / TES / UES', 'https://joinindianarmy.nic.in/', 'Notification: twice yearly (typical)', '₹56,100+ (Level 10) + Military Service Pay', '10+2 with PCM for TES; graduate for other entries', ARRAY['defence','army','ssb']),
('GOV027', 'Flying / Technical / Ground Duty Officer', 'Indian Air Force (AFCAT)', 'DEFENCE', ARRAY['ALL'], NULL, 'AFCAT', 'https://afcat.cdac.in/', 'Notification: Jun & Dec (twice yearly, typical)', '₹56,100+ (Level 10) + Military Service Pay', 'Graduate/Engineering depending on branch', ARRAY['defence','airforce']),
('GOV028', 'Short Service Commission Officer', 'Indian Navy (SSC)', 'DEFENCE', ARRAY['CSE','ECE','MECH'], NULL, 'Indian Navy SSC Entry', 'https://www.joinindiannavy.gov.in/', 'Notification: varies, check official site', '₹56,100+ (Level 10) + Military Service Pay', 'B.E/B.Tech relevant branch', ARRAY['defence','navy']),
('GOV029', 'Assistant Commandant', 'Central Armed Police Forces (CAPF AC)', 'DEFENCE', ARRAY['ALL'], NULL, 'UPSC CAPF AC Exam', 'https://www.upsc.gov.in/', 'Notification: Apr-May, Exam: Aug (typical)', '₹56,100 - ₹1,77,500 (Level 10)', 'Any graduate, age 20-25', ARRAY['defence','paramilitary']),
('GOV030', 'Head Constable', 'Border Security Force (BSF)', 'DEFENCE', ARRAY['ALL'], NULL, 'BSF Head Constable Recruitment', 'https://rectt.bsf.gov.in/', 'Notification: varies', '₹25,500 - ₹81,100 (Level 4)', '12th pass with relevant experience/diploma', ARRAY['defence','paramilitary','entry-level']),

-- Other Central (SSC/UPSC)
('GOV031', 'Combined Graduate Level (various posts)', 'Staff Selection Commission (SSC CGL)', 'CENTRAL_GOVT', ARRAY['ALL'], NULL, 'SSC CGL', 'https://ssc.nic.in/', 'Notification: Jun-Jul, Tier 1: Sep (typical)', '₹25,500 - ₹1,51,100 depending on post', 'Any graduate, age 18-32', ARRAY['central','all-graduates','ssc']),
('GOV032', 'Combined Higher Secondary Level (various posts)', 'Staff Selection Commission (SSC CHSL)', 'CENTRAL_GOVT', ARRAY['ALL'], NULL, 'SSC CHSL', 'https://ssc.nic.in/', 'Notification: Apr-May (typical)', '₹19,900 - ₹63,200 depending on post', '12th pass, age 18-27', ARRAY['central','12th-pass','ssc']),
('GOV033', 'Central Police Organisation (SI/ASI)', 'Staff Selection Commission (SSC CPO)', 'CENTRAL_GOVT', ARRAY['ALL'], NULL, 'SSC CPO', 'https://ssc.nic.in/', 'Notification: Sep-Oct (typical)', '₹35,400 - ₹1,12,400 (Level 6)', 'Any graduate, age 20-25', ARRAY['central','police','ssc']),
('GOV034', 'Civil Services (IAS/IPS/IFS etc.)', 'Union Public Service Commission (UPSC CSE)', 'CENTRAL_GOVT', ARRAY['ALL'], NULL, 'UPSC Civil Services Exam', 'https://www.upsc.gov.in/', 'Notification: Feb, Prelims: May-Jun (typical)', '₹56,100 - ₹2,50,000 depending on rank/service', 'Any graduate, age 21-32', ARRAY['central','civil-services','upsc']),
('GOV035', 'State Civil Services (SDM/DySP etc.)', 'Uttar Pradesh Public Service Commission (UPPSC)', 'STATE_GOVT', ARRAY['ALL'], NULL, 'UPPSC Combined State/Upper Subordinate Exam', 'https://uppsc.up.nic.in/', 'Notification: varies, annual cycle', 'As per post (Pay Matrix Level 6-11)', 'Any graduate, age 21-40', ARRAY['state','up','administrative']);
